### ISSUE TITLE
Support gpsd

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/packet_forwarder#21]
Allow the option to use gpsd to get coordinates, rather than directly from the gps. Some gateways wants to synchronise time using the gps. Two applications can not have the gps path open at the same time. A solution is to use gpsd in between. NTP already supports gpsd.

See for example:
http://www.satsignal.eu/ntp/Raspberry-Pi-NTP.html

GPSD should be an option, not a replacement for the current direct tty interface. GPSD adds overhead which some people don't need and don't want.

**Comment by egourlao** [comment]
Closed by #46
