### ISSUE TITLE
This link to Kerlink build is broken

### ISSUE THREAD

**Issue by wienke** [TheThingsNetwork/packet_forwarder#22]
<img width="412" alt="schermafbeelding 2017-05-10 om 19 18 17" src="https://cloud.githubusercontent.com/assets/3216553/25911800/7753b434-35b5-11e7-99e1-5b03904ef932.png">

**Comment by egourlao** [comment]
The link is now [fixed in develop](https://github.com/TheThingsNetwork/packet_forwarder/blob/develop/docs/INSTALL_INSTRUCTIONS/KERLINK.md), which will be merged as soon as v2.0.2 is released (probably today).
