### ISSUE TITLE
Gateways don't appear on the community map

### ISSUE THREAD

**Issue by egourlao** [TheThingsNetwork/packet_forwarder#23]
Gateways that have their location specified on the console don't appear on the map anymore.

Example:
* [This gateway](https://console.thethingsnetwork.org/gateways/g1-test) is set on the console as near Lucerne, Switzerland.
* However, it doesn't appear on the community map [here](https://www.thethingsnetwork.org/community/Zentralschweiz/).
* From what it seems, the [NOC](http://noc.thethingsnetwork.org:8085/api/v2/gateways/g1-test) doesn't know the location either.

**Comment by johanstokking** [comment]
When not using the bridge but gRPC with the Router instead, the gateway should provide the location itself. It gets the location from the Account Server and adds it as part of the messages to the Router.
