### ISSUE TITLE
Gateway uptime printed to std out overflows/rolls over after 1h11m21s

### ISSUE THREAD

**Issue by h0l0gram** [TheThingsNetwork/packet_forwarder#26]
I started packet forwarder with `./packet-forwarder-linux-arm-imst_rpi-native start -v`
After 6h the reported uptime with the status log message shows 55m.

Thus I waited to see when the roll-over happens:

*Gateway: g1-test*

```
  INFO Sending status to the network server     CpuPercentage=0.38904092 FrequencyPlan=EU_863_870 Load1=0.02 Load15=0.11 Load5=0.06 MemoryPercentage=13.361667 RXPacketsReceived=746 RXPacketsValid=746 TXPacketsReceived=0 TXPacketsValid=0 Uptime=1h11m21.54814s
  INFO Sending status to the network server     CpuPercentage=0.38904974 FrequencyPlan=EU_863_870 Load1=0.02 Load15=0.11 Load5=0.06 MemoryPercentage=13.361667 RXPacketsReceived=746 RXPacketsValid=746 TXPacketsReceived=0 TXPacketsValid=0 Uptime=1.657196s
  INFO Sending status to the network server     CpuPercentage=0.3890548 FrequencyPlan=EU_863_870 Load1=0.01 Load15=0.11 Load5=0.05 MemoryPercentage=13.361667 RXPacketsReceived=746 RXPacketsValid=746 TXPacketsReceived=0 TXPacketsValid=0 Uptime=16.716354s
  INFO Sending status to the network server     CpuPercentage=0.38906047 FrequencyPlan=EU_863_870 Load1=0.01 Load15=0.1 Load5=0.05 MemoryPercentage=13.361667 RXPacketsReceived=746 RXPacketsValid=746 TXPacketsReceived=0 TXPacketsValid=0 Uptime=31.77687s
```

**Comment by egourlao** [comment]
The reason for the bug is that the value used as `Uptime` is a [`status.Timestamp`](https://github.com/TheThingsNetwork/ttn/blob/develop/api/gateway/gateway.pb.go#L304) value, that is originally the concentrator's uptime. However, it is intended, according to the proto, that the value rollovers before it's sent to the network server.
I'll remove it from the logs, so that it doesn't create any more confusion.

**Comment by h0l0gram** [comment]
What about "boottime"? Can this be logged to indicate when packet forwarder is started?

**Comment by egourlao** [comment]
I think it could be logged. I'll add it.

**Comment by h0l0gram** [comment]
`bootTime` is the time when the packet forwarder was started isn't it?
`bootTime - currentTime` would be the `uptime` then?

**Comment by egourlao** [comment]
`currentTime - bootTime` would be the `uptime`, yes! I'll try to see if we can directly log the correct value of `uptime`.
