### ISSUE TITLE
Incorrect URL in doc for IMST+RaspberryPi

### ISSUE THREAD

**Issue by ernstdevreede** [TheThingsNetwork/packet_forwarder#31]
The documentation  for the IMST+RaspBerryPi gateway in docs/INSTALL_INSTRUCTIONS/IMST_RPI.md has an incorrect download link for the binary; it should be
 https://ttnreleases.blob.core.windows.net/packet-forwarder/master/imst-rpi-pktfwd.tar.gz

**Comment by egourlao** [comment]
Thank you. This is now [fixed in the `develop` branch](https://github.com/TheThingsNetwork/packet_forwarder/commit/e3087ef8e53f92fd197d347359cd5ff11ca623b8), and will subsequently be applied in `master`.
