### ISSUE TITLE
Reset pin documentation

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/packet_forwarder#47]
This is a feature request for the packet forwarder documentation.

Make a table of common reset pin values for the Raspberry Pi setup.

**Comment by egourlao** [comment]
Apart from this, it will also probably necessary to document how to use the gpio pins without being root: https://github.com/stianeikeland/go-rpio#using-without-root

**Comment by tomazursic** [comment]
For user with sudo permissions was enough to add user to group `gpio` to make the `reset-pin`.
It works without using `create_gpio_user_permissions.py`

The "reset-pin" for [IMST ic880a](http://webshop.imst.de/radio-modules/lora-concentrators.html) is **"25"** also with [IMST iC880a LoRaWAN backplane](https://www.tindie.com/products/gnz/imst-ic880a-lorawan-backplane-kit/).

**Comment by xenek** [comment]
Per https://github.com/jpmeijers/ttn-resin-gateway-rpi
I can confirm that reset pin 26 is correct for the Rising HF Raspberry Pi Shield using v2.0.2 of the TTN new packet forwarder. Must be specified.
x
