### ISSUE TITLE
Timestamp for each log entry

### ISSUE THREAD

**Issue by h0l0gram** [TheThingsNetwork/packet_forwarder#49]
This is a **{feature request}** for **{the packet forwarder}**.

It would be nice to have a timestamp for each line the packet forwarder prints to console or log file.
This helps to now when which event happened.

Something like:

```2017-06-08 14:33:20.432 INFO Received Uplink```

**Comment by johanstokking** [comment]
`systemd` and `docker` does it for you, among other ways to run this process as a service. I don't think it belongs to the output.

What may be useful instead, is a way to specify a custom log driver so you can do whatever there. Raise a new issue if that is something of interest.
