### ISSUE TITLE
Clarify build compatibility for Raspberry Pi models

### ISSUE THREAD

**Issue by mkilchhofer** [TheThingsNetwork/packet_forwarder#54]
I already successfully the v2.0.2 packet_forwarder on different raspberry pi 3 with the iC880A concentrator.
I now tried to plug the sd card of a finished installation into a Raspberry Pi Zero.
This is the result:
```
root@bfh-mobgw1:/opt/imst-rpi-pktfwd# ./packet-forwarder 
Illegal instruction
root@bfh-mobgw1:/opt/imst-rpi-pktfwd# ./packet-forwarder start --config /etc/packet_forwarder.yml
Illegal instruction
```
Do you support the Pi Zero?
```
root@bfh-mobgw1:/opt/imst-rpi-pktfwd# cat /proc/cpuinfo 
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 900093
Serial		: 00000000bf4877d8
```

## Environment

- `<packet-forwarder> version` returns: `Commit={...}`
- My gateway:
  - Manufacturer: `IMST GmbH`
  - Type of concentrator: `iC880A`
  - Type of interface with the concentrator: `SPI`
- Is connected to: `The TTN community network`

**Comment by mkilchhofer** [comment]
I built the `packet-forwarder` as described in the file `INSTALL_INSTRUCTIONS` directly on the Pi Zero.
Now it works :+1:

**Comment by egourlao** [comment]
Glad to hear it works now!

Given how you resolved the issue, it is probably linked to the fact that the release packet forwarder for Raspberry Pis is built for ARMv6 instruction sets, whereas the `INSTALL_INSTRUCTIONS` file indicates to use the `GOARM=7` parameter (for ARMv7 instruction sets). It's not the first time that I heard about this kind of errors (with other users wanting to run the packet forwarder on Raspberry Pi A+/B+ models, for example). I think it would be relevant to add some sort of table in the documentation, for example, detailing how to build the packet forwarder for every kind of Raspberry Pis - and potentially, add those build processes to our [CI pipeline](https://github.com/TheThingsNetwork/packet_forwarder/blob/master/.gitlab-ci.yml).

**Comment by christopherdro** [comment]
Here is a basic breakdown of Pi architectures.

## Model A 
- ARMv6Z (32-bit) 
## Model B
 - ARMv7-A(32-bit) **(Gen 2)**
 - ARMv8-A (64/32-bit) **(Gen 2 ver 1.2 and Gen 3)**

## Zero 
- ARMv6Z (32-bit)

Do we want to add the build commands for arm 6 and 8 to the existing [step](https://github.com/TheThingsNetwork/packet_forwarder/blob/master/.gitlab-ci.yml#L86), or create individual ones for each?
