### ISSUE TITLE
Failed to start concentrator on BBB and IMST

### ISSUE THREAD

**Issue by danielknox** [TheThingsNetwork/packet_forwarder#56]
This is a question for the Things Network version of the packet forwarder (built on go). This gateway has successfully been running a previous (c only) version of the semtech gateway and packet forwarder.

I've built the Things Network Packet Forwarder on a custom Beaglebone black with a IMST i880a card. SPI has been configured correctly for this device (lorank chosen in library.cfg) and after compiling the go program, I used util_tx_continuous to test communicating with the board - this worked and the IMST board lit up the appropriate lights. However, when I start the packet forwarder I get:

> INFO Starting concentrator...                 DateTime=2017-06-21 10:42:45.328982478 +0000 UTC
> ERROR The program ended following a failure    error=Failed to start concentrator

I've tried the usual resetting the board and have confirmed the concentrator can be started using my old setup. Any clues what's up / a way of getting a little more useful information out of this. It looks like the go program is successfully communicating with the board to configure it, just failing to start the actual concentrator.

>  INFO Found gateway parameters, getting frequency plans AuthServer=https://account.thethingsnetwork.org GatewayID=shedgateway1 URL=https://account.thethingsnetwork.org/api/v2/frequency-plans/EU_863_870
>   INFO Refreshed account server information     TokenExpiry=2017-09-22 10:42:45.004582129 +0000 UTC
>   INFO Connecting to TTN discovery server       Address=discover.thethingsnetwork.org:1900
>   INFO Connected to discovery server - getting router address
>   INFO Connecting to router...                  RouterID=ttn-router-eu
>   INFO SX1301 board configured                  ClockSource=1 LorawanPublic=true
>   INFO Configured TX Lut                        Indexes=16
>   INFO Radio configured                         EnabledTX=true Frequency=867500000 RSSIOffset=-166 Radio=0 Type=SX1257
>   INFO Radio configured                         EnabledTX=false Frequency=868500000 RSSIOffset=-166 Radio=1 Type=SX1257
>   INFO LoRa multi-SF channel configured         Freq=-400000 Lora multi-SF channel=0 RFChain=1
>   INFO LoRa multi-SF channel configured         Freq=-200000 Lora multi-SF channel=1 RFChain=1
>   INFO Downlinks queuing routine started       
>   INFO LoRa multi-SF channel configured         Freq=0 Lora multi-SF channel=2 RFChain=1
>   INFO LoRa multi-SF channel configured         Freq=-400000 Lora multi-SF channel=3 RFChain=0
>   INFO LoRa multi-SF channel configured         Freq=-200000 Lora multi-SF channel=4 RFChain=0
>   INFO LoRa multi-SF channel configured         Freq=0 Lora multi-SF channel=5 RFChain=0
>   INFO LoRa multi-SF channel configured         Freq=200000 Lora multi-SF channel=6 RFChain=0
>   INFO LoRa multi-SF channel configured         Freq=400000 Lora multi-SF channel=7 RFChain=0
>   INFO LoRa standard channel configured  

## Environment

- `<packet-forwarder> version` returns: `Commit={...}`
- My gateway:
  - Manufacturer: `{beaglebone black}`
  - Type of concentrator: `{imst}`
  - Type of interface with the concentrator: `spi`
- Is connected to: `{The TTN community network}`

**Comment by LoRa-YvAd** [comment]
The same problem on RPi3B:
ERROR The program ended following a failure    error=Failed to start concentrator

**Comment by dmamalis** [comment]
@LoRa-YvAd have you managed to have the concentrator started with other methods like the Semtech packet forwarder? It seems that there is a quite specific issue with SPI not working correctly on some RPi3B batches. 
You can check the following links but I have to admit that I have had RPis that haven't managed to start the concentrator no matter what. Unfortunately I never had the luck to check that on a logic analyzer.

https://github.com/Lora-net/lora_gateway/issues/49
https://github.com/Lora-net/lora_gateway/issues/66
https://github.com/Lora-net/lora_gateway/issues/26

Please let us know of your progress!

**Comment by LoRa-YvAd** [comment]
The issue starter has the problem on a Beaglebone...I fiddled with the reset pins, changed power supplies, tried the 'Zurich approach, the 'new' packet forwarder and sniffed at the polypacket forwarder before finally changing to something that worked 'straight out of the box' : https://github.com/jpmeijers/ttn-resin-gateway-rpi
Pitty I had to take the gateway offline, because I have to rebuild my hobby attick, but as soon as my network is back up again, the gateway will follow!
