### ISSUE TITLE
Forwarder doesn't restart on momentary network outages

### ISSUE THREAD

**Issue by terrillmoore** [TheThingsNetwork/packet_forwarder#65]
This is a **bug report** for **the packet forwarder**.

- I am using the TTN Packet Forwarder on a MultiTech Conduit
  * `uname -a` on the Conduit: `Linux ttn-nyc-1140_6th_mcci_production 3.12.27 #1 Thu May 5 18:53:23 CDT 2016 armv5tejl GNU/Linux`
  * I am using [V2.0.2](https://github.com/TheThingsNetwork/packet_forwarder/releases/tag/v2.0.2) of the TTN packet forwarder.
  * I am using Jeff Honig's [Ansible provisioner for Condit](https://github.com/IthacaThings/ttn-multitech-cm.git), which does the work to convert the release into an .ipk file.

- I use `/etc/init.d/ttn-pkt-forwarder`, locally modified to preserve the log file. File is attached as a zip:
[ttn-pkt-forwarder.zip](https://github.com/TheThingsNetwork/packet_forwarder/files/1154332/ttn-pkt-forwarder.zip).  This preserves the log file in `/var/log/lora-pkt.log`.

- The packet forwarder exits periodically, leaving the gateway non-functional until I notice that the forwarder is dead and manually restart it. This is obviously bad for production. 

- There is no other evidence of anything other than transient network problems.  The network is part of an office building, probably with several layers of NATing.

- The old Kersing packet forwarder (V2) ran for months in the same environment without difficulty.

- It is possible that a firewall/router upstream is causing the TCP connection to be dropped, either due to NAT table aging or slight instability.

- This failure results in **loss of data**, as there is no other gateway coverage for this experiment.

## Expected Behavior
- The pkt-forwarder should try to reconnect a few times with a timeout if the connection is dropped, prior to giving up.  While it's possible to wrap this with a process, the pkt-forwarder has more knowledge about what kind of outage has caused this -- "connection reset by peer" should cause a simple attempt to reestablish. If successful re-establishing, the retry count should be reset.  This would be enough to fix this problem.

## Log at shutdown

- Here is the relevant section of the log:
```
  INFO Sending status to the network server     Altitude=0 CpuPercentage=27.49416 FrequencyPlan=US_902_928 Latitude=40.75602 Load1=0.92 Load15=0.74 Load5=0.8 Longitude=-73.98285 MemoryPercentage=9.2206955 RTT=85 RXPacketsReceived=37 RXPacketsValid=120 TXPacketsReceived=0 TXPacketsValid=0 Uptime=5m34.969076s
  INFO Sending status to the network server     Altitude=0 CpuPercentage=27.494387 FrequencyPlan=US_902_928 Latitude=40.75602 Load1=0.79 Load15=0.73 Load5=0.78 Longitude=-73.98285 MemoryPercentage=9.079032 RTT=84 RXPacketsReceived=37 RXPacketsValid=120 TXPacketsReceived=0 TXPacketsValid=0 Uptime=5m50.080823s
2017/07/17 14:09:04 transport: http2Client.notifyError got notified that the client transport was broken read tcp 192.168.25.200:46375->13.66.229.235:1901: read: connection reset by peer.
2017/07/17 14:09:48 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: context deadline exceeded"; Reconnecting to {us-west.thethings.network:1901 <nil>}
 ERROR Program ended after one of the network links failed
  INFO Stopping downlink manager
  INFO Closing downlinks queue
  INFO Closing uplinks queue
  INFO Concentrator stopped gracefully
 ERROR The program ended following a failure    error=Status routine error: Network server health check error: Health check with the router failed source=(*Manager).startRoutines.func1: /builds/thethingsnetwork/packet_forwarder/gopath/src/github.com/TheThingsNetwork/packet_forwarder/pktfwd/manager.go:284
```

## Environment

- `<packet-forwarder> version` returns: 
```
  INFO Got build information                    BuildDate=2017-06-07T07:5554Z Commit=b64203b985c02a82ab4f3cb41d907be85fcb04e6 Version=
```
- My gateway:
  - Manufacturer: Multi-Tech
  - OS: mLinux; `Linux ttn-nyc-1140_6th_mcci_production 3.12.27 #1 Thu May 5 18:53:23 CDT 2016 armv5tejl GNU/Linux`
  - Type of concentrator: MTAC (old style, FTDI, not raw SPI).
  - Type of interface with the concentrator: USB
- Is connected to: The TTN community network

**Comment by SloMusti** [comment]
I am observing the same issue, see above referenced ticket.

**Comment by egourlao** [comment]
@SloMusti The logs mentioned in [this issue](https://github.com/jpmeijers/ttn-resin-gateway-rpi/issues/7) are logs written by the `mp-pkt-fwd`, for which you can find the repository [here](https://github.com/kersing/packet_forwarder). The development of the TTN packet forwarder is on hold for the moment!

**Comment by SloMusti** [comment]
@kersing maintaining the `mp-pkt-fwd` has been notified of the issue and is working on it.
