### ISSUE TITLE
Does packet_forward support SX1301AP2?

### ISSUE THREAD

**Issue by ChunChiehKung** [TheThingsNetwork/packet_forwarder#66]
This is a question  for the packet forwarder.
We have SX1301AP2 which has FPGA inside.
It's not native SPI.
Does packet_forward support SX1301AP2?
Please advise.
Thanks.

**Comment by egourlao** [comment]
The packet forwarder doesn't support SX1301AP2 modules yet, although we are planning to support them in the future.
