### ISSUE TITLE
Please provide a stripped binary

### ISSUE THREAD

**Issue by jchonig** [TheThingsNetwork/packet_forwarder#68]
This is a **bug report** for **{the packet forwarder}**.

The binary installed is very huge.  The binary is 100 times as big as it should be.  Please provide a stripped binary in the tarball and build the ipk from that by default.  Users who would like a debugging binary should be able to request that but it should not be the default.

## Environment

Multi-Tech Conduit mLinux 3.3.7
Version 2.0.2

**Comment by egourlao** [comment]
The pull request #70 reduces the binary size from 11Mb to 3Mb, let us know what you think about it!
