### ISSUE TITLE
Makefile:52: *** [error] Can't find configuration for SPI phy.  Stop.

### ISSUE THREAD

**Issue by thayuriko** [TheThingsNetwork/packet_forwarder#74]
I'm new at this and when I'm trying to install the packet_forwarder from the legacy branch but it keeps giving me this error from the title.
I first cloned the lora_gateway and packet_forwarder (legacy branch), then used "make" command on the lora_gateway folder, but when I did the same for the packet_forwarder, it returned me the following:
```
make all -e -C basic_pkt_fwd
make[1]: Entering directory '/home/rxhf/ttn/packet_forwarder/legacy/basic_pkt_fwd'
Makefile:52: *** [error] Can't find configuration for SPI phy.  Stop.
make[1]: Leaving directory '/home/rxhf/ttn/packet_forwarder/legacy/basic_pkt_fwd'
Makefile:11: recipe for target 'all' failed
make: *** [all] Error 2
```

## Environment

- version 2.1.0
- My gateway:
  - Manufacturer: `RPi3`
  - Type of concentrator: `RHF0M301`

**Comment by christopherdro** [comment]
@thayuriko Is there a specific reason your trying to use the legacy packet forwarder?

You should be able to download and use the binary for the Raspberry Pi + IMST build with your Pi3 and RHF0M301.

https://ttnreleases.blob.core.windows.net/packet-forwarder/master/imst-rpi-pktfwd.tar.gz
