### ISSUE TITLE
wrapper doesn't link libmpsse

### ISSUE THREAD

**Issue by jeremyherbert** [TheThingsNetwork/packet_forwarder#83]
When building the packet forwarder, I get the following errors:

```
# github.com/TheThingsNetwork/packet_forwarder/wrapper
wrapper/../lora_gateway/libloragw/libloragw.a(loragw_spi.o): In function `lgw_spi_open':
loragw_spi.ftdi.c:(.text+0x38): undefined reference to `OpenIndex'
loragw_spi.ftdi.c:(.text+0x5a): undefined reference to `PinLow'
loragw_spi.ftdi.c:(.text+0x6a): undefined reference to `PinHigh'
wrapper/../lora_gateway/libloragw/libloragw.a(loragw_spi.o): In function `lgw_spi_close':
loragw_spi.ftdi.c:(.text+0xaa): undefined reference to `Close'
wrapper/../lora_gateway/libloragw/libloragw.a(loragw_spi.o): In function `lgw_spi_w':
loragw_spi.ftdi.c:(.text+0xfa): undefined reference to `Start'
loragw_spi.ftdi.c:(.text+0x10a): undefined reference to `FastWrite'
loragw_spi.ftdi.c:(.text+0x117): undefined reference to `Stop'
wrapper/../lora_gateway/libloragw/libloragw.a(loragw_spi.o): In function `lgw_spi_r':
loragw_spi.ftdi.c:(.text+0x1b8): undefined reference to `Start'
loragw_spi.ftdi.c:(.text+0x1c8): undefined reference to `Transfer'
loragw_spi.ftdi.c:(.text+0x1d3): undefined reference to `Stop'
wrapper/../lora_gateway/libloragw/libloragw.a(loragw_spi.o): In function `lgw_spi_wb':
loragw_spi.ftdi.c:(.text+0x2fe): undefined reference to `Start'
loragw_spi.ftdi.c:(.text+0x397): undefined reference to `FastWrite'
loragw_spi.ftdi.c:(.text+0x3a8): undefined reference to `Stop'
wrapper/../lora_gateway/libloragw/libloragw.a(loragw_spi.o): In function `lgw_spi_rb':
loragw_spi.ftdi.c:(.text+0x599): undefined reference to `Start'
loragw_spi.ftdi.c:(.text+0x5ad): undefined reference to `FastWrite'
loragw_spi.ftdi.c:(.text+0x5d9): undefined reference to `FastRead'
loragw_spi.ftdi.c:(.text+0x5e8): undefined reference to `Stop'
collect2: error: ld returned 1 exit status
```

Looking closer at the files in the wrapper directory, it seems that the cgo flags are not set to link `libmpsse`. One cannot use `CGO_LDFLAGS` because the order of linker arguments matters, and that appends it onto the end of the existing args. The correct line in the various `wrapper/*.go` files should be:

```// #cgo LDFLAGS: -lm -lmpsse ${SRCDIR}/../lora_gateway/libloragw/libloragw.a```

Yes, I realise this breaks other the non-ftdi builds. Still trying to work out how to solve that.

## Environment

- commit hash: 225c5394e30330ef04c0557803ade3d23c0f4f32
- My gateway:
  - Manufacturer: None (it's a vagrant VM, ubuntu 16.04)
  - Type of concentrator: Multitech MTAC-LORA-915
  - Type of interface with the concentrator: FTDI

**Comment by jeremyherbert** [comment]
Given that a specific version of libmpsse is required, is there a reason that libmpsse isn't just included in this repository ? It could be bundled into libloragw fairly easily. I can provide a pull request for this.

**Comment by egourlao** [comment]
Thanks for your feedback! We're trying to keep the repository clean, so we'd like to avoid storing `libmpsse` in it. However, it would probably be a good idea to specify more explicitly in the docs which version of lmpsse to download, and how to install it.

**Comment by jeremyherbert** [comment]
I actually think that the docs for how to do it are pretty good. The problem for me here is that some linker flags are missing in the go wrapper.

**Comment by egourlao** [comment]
I'd rather not add those linker flags in the Go files, since `libmpsse` is only required for FTDI builds - for which we plan to drop support mid-term. It'd also mean every developer would have to install `libmpsse` to develop, even for SPI gateways...
Another solution could be to move *all* the cgo flags in the [Makefile](https://github.com/TheThingsNetwork/packet_forwarder/blob/master/.make/go/build.make#L5-L16). What do you think?

**Comment by jeremyherbert** [comment]
That sounds like a much better idea!

**Comment by jeremyherbert** [comment]
Do you have any plans to support a USB-based setup then?
