### ISSUE TITLE
Raspbian Stretch - Illegal instruction

### ISSUE THREAD

**Issue by cyber92** [TheThingsNetwork/packet_forwarder#85]
This is a bug report for the packet forwarder.

- Tried to run packet-forwarder
- Used compiled build Rpi + IMST 2.02
- Raspbian Stretch fully updated

> ttn@ttn-smarje:~ $ packet-forwarder
> Illegal instruction

Also tried with configure, but the same problem arises.

What can I do?

**Comment by x893** [comment]
The same error on RPi Zero W

**Comment by mportcode** [comment]
Pre build packet forwarder is for raspberry Pi3 which have different arm core than RPi Zero W.
If you would like to use this on RPi Zero or RPi 2 you must build it from source.

**Comment by christopherdro** [comment]
See https://github.com/TheThingsNetwork/packet_forwarder/blob/master/docs/INSTALL_INSTRUCTIONS/IMST_RPI.md#building-the-binary

Related #54
