### ISSUE TITLE
SPI 1301 module with FPGA(AP1.5)

### ISSUE THREAD

**Issue by ChunChiehKung** [TheThingsNetwork/packet_forwarder#89]
This is a **{question.}** for **{the packet forwarder}**.

Does current support LoRa AP1.5 which has a FPGA on the module?
If not, may I know what is the release code schedule?
Thanks a lot.

**Comment by egourlao** [comment]
This packet forwarder does not support the new chip format - and given that the development is on hold, it is not planned to support it.
