### ISSUE TITLE
Sending temperature in the status

### ISSUE THREAD

**Issue by egourlao** [TheThingsNetwork/packet_forwarder#9]
Currently, the packet forwarder does not send the temperature of the system to the back-end. This should be easy to implement, now that `gopsutil` provides a method to get the system temperature.

**Comment by JuanRamino** [comment]
Some references to `gopsutil/host` `SensorsTemperatures()`

[https://github.com/shirou/gopsutil/pull/334](https://github.com/shirou/gopsutil/pull/334)

**Comment by johanstokking** [comment]
@JuanRamino fancy to submit a pull request?

**Comment by JuanRamino** [comment]
On my Raspberry PI 0 W (ARMv6) `host.SensorsTemperatures()` return `[]`

See [https://github.com/shirou/gopsutil/issues/391](https://github.com/shirou/gopsutil/issues/391)
